<?php

return [
    'BASE_URL' => '/devpanel',
    'LOCALHOST_URL' => 'http://localhost',
    'PHPMYADMIN_URL' => 'http://localhost/phpmyadmin',
    'LAMPP_PATH' => '/opt/lampp',
    'HTDOCS_PATH' => '/opt/lampp/htdocs',
    'PHP_BINARY' => '/opt/lampp/bin/php',
    'APACHE_ERROR_LOG' => '/opt/lampp/logs/error_log',
    'APACHE_ACCESS_LOG' => '/opt/lampp/logs/access_log',
    'PHP_ERROR_LOG' => '/opt/lampp/logs/php_error_log',
    'MYSQL_DATA_DIR' => '/opt/lampp/var/mysql',
    'MYSQL_HOST' => '127.0.0.1',
    'MYSQL_PORT' => 3306,
    'MYSQL_USER' => 'root',
    'MYSQL_PASSWORD' => '',
    'GITHUB_USER' => '',
    'GITHUB_REPO' => '',
    'GITHUB_REMOTE_URL' => '',
    'EXCLUDED_PROJECT_FOLDERS' => ['dashboard', 'webalizer', 'xampp', 'phpmyadmin', 'devpanel'],
    'DEVPANEL_PASSWORD' => 'CHANGE_ME_WITH_BCRYPT_HASH',
    'DEVPANEL_2FA_ENABLED' => false,
    'DEVPANEL_2FA_SECRET' => '',
    'DEVPANEL_API_TOKENS' => [],
    'DEVPANEL_USERS' => [],
    'DEVPANEL_DEMO_MODE' => false,
    'DEVPANEL_MAINTENANCE_MODE' => false,
    'DEVPANEL_MAINTENANCE_MESSAGE' => 'DevPanel está en mantenimiento local.',
    'DEVPANEL_PLUGINS_ENABLED' => ['docker', 'database', 'git', 'backups', 'terminal', 'templates', 'domains'],
    'DEVPANEL_ROLES' => [
        'admin' => ['*'],
        'developer' => ['dashboard', 'projects', 'files', 'git', 'terminal', 'logs', 'backups', 'domains'],
        'viewer' => ['dashboard', 'logs'],
    ],
    'THEME' => 'dark',
    'AVAILABLE_THEMES' => ['dark', 'cyber', 'ubuntu', 'glass'],
];
